[命令修改] 修正命令描述
DuckDuckStudio/Chinese_git pull request #13
Opened 2024-06-21 13:04 UTC by DuckDuckStudio

2024-06-21 13:04 UTC, DuckDuckStudio commented
@fjwxzde set

2024-06-21 13:06 UTC, fjwxzde commented
@fjwxzde run test

2024-06-21 13:18 UTC, fjwxzde submitted a review, later dismissed
也许需要：
可能需要发布命令修改公告（竖起大拇指以赞同）

2024-06-21 13:19 UTC, Luna-Grace commented
> 也许需要： 可能需要发布命令修改公告（竖起大拇指以赞同）

你觉得呢 @DuckDuckStudio

2024-06-21 13:20 UTC, Luna-Grace reviewed
“清理分支”这个命令可能会引起误解...?

2024-06-21 13:22 UTC, DuckDuckStudio commented
> > 也许需要： 可能需要发布命令修改公告（竖起大拇指以赞同）
> 
> 你觉得呢 @DuckDuckStudio

我觉得需要。

2024-06-21 13:23 UTC, DuckDuckStudio commented
> “清理分支”这个命令可能会引起误解...?

但我现在也只能想到这个名称了...

2024-06-21 13:42 UTC, Luna-Grace requested changes
`清理本地引用`会不会好点

2024-06-21 13:44 UTC, DuckDuckStudio commented
@fjwxzde pack

2024-06-21 13:50 UTC, fjwxzde requested changes
版本号错误

2024-06-21 13:55 UTC, DuckDuckStudio commented
@fjwxzde run test

2024-06-21 13:56 UTC, fjwxzde approved these changes

2024-06-21 14:02 UTC, Luna-Grace approved these changes

2024-06-21 14:06 UTC, merged

2024-06-24 13:55 UTC, DuckDuckStudio commented
此PR的内容在 #16 中再次修改。