refactor: 使用C#重写部分程序
DuckDuckStudio/Chinese_git pull request #39
Opened 2024-07-26 07:45 UTC by Luna-Grace

进展中...

2024-07-26 13:08 UTC, DuckDuckStudio commented
CodeQL Java → ERROR

2024-07-26 13:33 UTC, DuckDuckStudio commented
阶段性预览版 [v2.9.1](https://github.com/DuckDuckStudio/Chinese_git/releases/tag/v2.9.1) 已发布

2024-11-28 15:14 UTC, DuckDuckStudio requested changes
C# 中输出前加 `$` 应该和 Python 的 `f` 差不多吧

2024-11-28 15:14 UTC, DuckDuckStudio commented on C#/中文git/Program.cs
> +                    Console.WriteLine($"✕ 无法获取最新默认配置文件");
```suggestion
                    Console.WriteLine("✕ 无法获取最新默认配置文件");
```

2024-11-28 15:14 UTC, DuckDuckStudio commented on C#/中文git/Program.cs
> +                    Console.WriteLine($"✕ 生成默认配置文件时出错！请手动添加配置文件，否则某些功能可能无法正常运行！");
```suggestion
                    Console.WriteLine("✕ 生成默认配置文件时出错！请手动添加配置文件，否则某些功能可能无法正常运行！");
```

2024-11-28 15:14 UTC, DuckDuckStudio commented on C#/中文git/Program.cs
> +                        Information = new Information { Version = "v2.9" },
```suggestion
                        Information = new Information { Version = "v2.11" },
```

Bump version to v2.11

2024-11-28 15:14 UTC, DuckDuckStudio commented on C#/中文git/Program.cs
> +                Console.WriteLine($"⚠ 没有找到配置文件，将生成默认配置文件！");
```suggestion
                Console.WriteLine("⚠ 没有找到配置文件，将生成默认配置文件！");
```

2024-11-30 08:38 UTC, Luna-Grace commented on C#/中文git/Program.cs
> +                        Information = new Information { Version = "v2.9" },
确定？

Bump version to v2.10-1 会不会好点？

2024-11-30 08:43 UTC, Luna-Grace commented
@DuckDuckStudio 

- #81 合并后应该就没有冲突了

2024-11-30 08:47 UTC, DuckDuckStudio commented on C#/中文git/Program.cs
> +                        Information = new Information { Version = "v2.9" },
那先不改

2025-06-10 03:02 UTC, closed without merging

2025-06-10 03:02 UTC, DuckDuckStudio commented
过时